language: php

php:
  - 5.5

services:
  - mongodb

install:
  - composer install --prefer-source --no-interaction --dev

before_script:
  - phpenv config-add travisconfig.ini
  - sleep 3
  - php artisan generate:migration add_statements --path=app/database/migrations
  - php artisan migrate --env="testing"

script: ./vendor/bin/phpunit