language: php

php:
  - 5.5

services:
  - mongodb

install:
  - composer install --prefer-source --no-interaction --dev

before_script:
  - sleep 30
  - php artisan generate:migration add_statements
  - php artisan migrate --env="testing"

script: ./vendor/bin/phpunit