version: 2
dependencies:
  pre:
    - touch .env
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
      - image: redis:4-alpine
    environment:
      MONGODB_TEST_PATH: mongodb://localhost:27017/llv2tests
      TEST_API_PORT: 8080
      TEST_LOG_MIN_LEVEL: info
      APP_SECRET: 44E52D2227F93179525E252EC3AB5
      QUEUE_PROVIDER: REDIS
      REDIS_HOST: localhost
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - hardsource-cache-{{ .Branch }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Create empty .env
          command: touch .env
      - run:
          name: Testing Compile
          command: npm run build-all
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: hardsource-cache-{{ .Branch }}
          paths:
            - api/src/node_modules/.cache
            - ui/src/node_modules/.cache
            - cli/src/node_modules/.cache
            - worker/src/node_modules/.cache
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run integration tests
          command: npm run ci-test-integrations

  release:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
    environment:
    steps:
      - checkout
      - run:
          name: Run semantic release
          command: npm run semantic-release


workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: circleci
      - release:
          requires:
            - test
          filters:
            branches:
              only: master