version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
    environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Testing Compile
          command: npm run build-all
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run integration tests
          command: npm run ci-test-integrations
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  release:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
    environment:
    steps:
      - checkout
      - run:
          name: Run semantic release
          command: npm run semantic-release


workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: circleci
      - release:
          requires:
            - build
          filters:
            branches:
              only: master