version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4.4-jessie
    environment:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Testing Compile
          command: npm run build-all
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4.4-jessie
    environment:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm run lint
      - run:
          name: Installing Dependencies
          command: npm run test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: circleci
      - lint:
          requires:
            - build
          filters:
            branches:
              only: circleci