version: 2
dependencies:
  pre:
    - touch .env
orbs:
  cypress: cypress-io/cypress@1
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
      - image: redis:4-alpine
      - image: cypress/base:8
        environment:
          TERM: xterm
    environment:
      MONGODB_PATH: mongodb://localhost:27017/ll_integration_test
      MONGODB_TEST_PATH: mongodb://localhost:27017/ll_tests
      QUEUE_PROVIDER: REDIS
      REDIS_HOST: 127.0.0.1
      API_HOST: 127.0.0.1
      API_PORT: 8080
      TEST_API_PORT: 8080
      UI_HOST: 127.0.0.1
      UI_PORT: 3000
      APP_SECRET: 44E52D2227F93179525E252EC3AB5
      SITE_URL: "http://127.0.0.1:3000"
      TEST_LOG_MIN_LEVEL: info
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cache-{{ .Branch }}-{{ .Revision }}
            - v3-cache-{{ .Branch }}
            - v3-cache
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Create empty .env
          command: touch .env
      - run:
          name: Testing Compile
          command: npm run build-all
      - save_cache:
          key: v3-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules
            - api/src/node_modules/.cache
            - ui/src/node_modules/.cache
            - cli/src/node_modules/.cache
            - worker/src/node_modules/.cache
            - .cache
      - run:
          name: Run integration tests
          command:  |
            npm install pm2
            npm run start-test
            $(npm bin)/cypress run --config videoRecording=false
            yarn stop-test
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

  release:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
    environment:
    steps:
      - checkout
      - run:
          name: Run semantic release
          command: npm run semantic-release


workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: circleci
      - release:
          requires:
            - test
          filters:
            branches:
              only: master